const Product = require('../models/Product');

const sampleProducts = [
  // ─── Sports: Real Madrid ───────────────────────────────────────────────
  {
    name: 'Real Madrid Home Jersey 2024/25',
    description: 'Official Real Madrid home kit for the 2024/25 season. Lightweight, breathable fabric with iconic white design and gold trim.',
    price: 2499,
    comparePrice: 3200,
    category: 'clothing',
    franchise: 'Real Madrid',
    franchiseType: 'sports',
    tags: ['football', 'jersey', 'real madrid', 'la liga'],
    images: ['https://images.unsplash.com/photo-1606813907291-d86efa9b94db?q=80&w=800'],
    sku: 'RM-HOME-2425-M',
    stock: 50,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White'],
    rating: { average: 4.8, count: 320 },
  },
  {
    name: 'Real Madrid Scarf – Champions Edition',
    description: 'Premium wool-blend scarf in iconic Real Madrid colors. Perfect for match days or casual wear.',
    price: 799,
    comparePrice: 1200,
    category: 'accessories',
    franchise: 'Real Madrid',
    franchiseType: 'sports',
    tags: ['scarf', 'real madrid', 'accessories'],
    images: ['https://images.unsplash.com/photo-1600180758890-6b94519a8ba6?q=80&w=800'],
    sku: 'RM-SCARF-CE-001',
    stock: 120,
    sizes: [],
    colors: ['White', 'Purple'],
    rating: { average: 4.5, count: 88 },
  },
  // ─── Sports: Mumbai Indians ────────────────────────────────────────────
  {
    name: 'Mumbai Indians IPL Jersey 2024',
    description: 'Official Mumbai Indians T20 jersey. DryFit technology, bold blue with gold trim.',
    price: 1799,
    comparePrice: 2400,
    category: 'clothing',
    franchise: 'Mumbai Indians',
    franchiseType: 'sports',
    tags: ['cricket', 'ipl', 'jersey', 'mumbai indians'],
    images: ['https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=800'],
    sku: 'MI-JERSEY-2024-L',
    stock: 80,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Blue'],
    rating: { average: 4.7, count: 512 },
  },
  {
    name: 'Mumbai Indians Cap – Paltan Edition',
    description: 'Structured six-panel cap with embroidered MI logo. Adjustable strap for perfect fit.',
    price: 599,
    category: 'accessories',
    franchise: 'Mumbai Indians',
    franchiseType: 'sports',
    tags: ['cap', 'cricket', 'ipl', 'mumbai indians'],
    images: ['https://images.unsplash.com/photo-1588850561407-ed78c282e89b?q=80&w=800'],
    sku: 'MI-CAP-PE-001',
    stock: 200,
    sizes: ['One Size'],
    colors: ['Blue', 'Gold'],
    rating: { average: 4.6, count: 230 },
  },
  // ─── Sports: Chicago Bulls ─────────────────────────────────────────────
  {
    name: 'Chicago Bulls Classic Hoodie',
    description: 'Vintage-feel heavyweight fleece hoodie with iconic Bulls logo embroidery. Street-ready.',
    price: 2999,
    comparePrice: 3800,
    category: 'clothing',
    franchise: 'Chicago Bulls',
    franchiseType: 'sports',
    tags: ['nba', 'basketball', 'hoodie', 'bulls'],
    images: ['https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=800'],
    sku: 'CB-HOOD-CLS-001',
    stock: 60,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Red', 'Black'],
    rating: { average: 4.9, count: 178 },
  },
  {
    name: 'Chicago Bulls Retro Sneakers',
    description: 'Limited edition Bulls colourway low-top sneakers. Cushioned sole with herringbone grip.',
    price: 5499,
    comparePrice: 7000,
    category: 'shoes',
    franchise: 'Chicago Bulls',
    franchiseType: 'sports',
    tags: ['nba', 'sneakers', 'bulls', 'retro'],
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=800'],
    sku: 'CB-SNKR-RETRO-42',
    stock: 30,
    sizes: ['UK6', 'UK7', 'UK8', 'UK9', 'UK10', 'UK11'],
    colors: ['Red', 'White', 'Black'],
    rating: { average: 4.7, count: 95 },
  },
  // ─── Movie: Avengers ───────────────────────────────────────────────────
  {
    name: 'Avengers Endgame Collector Tee',
    description: 'High-quality 100% cotton tee with full-colour Endgame artwork print. Preshrunk, ribbed collar.',
    price: 999,
    category: 'clothing',
    franchise: 'Avengers',
    franchiseType: 'movie',
    tags: ['marvel', 'avengers', 'endgame', 'tshirt'],
    images: ['https://images.unsplash.com/photo-1608889825103-eb5ed706fc64?q=80&w=800'],
    sku: 'AVG-TEE-EG-M',
    stock: 150,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black'],
    rating: { average: 4.6, count: 640 },
  },
  {
    name: 'Iron Man Arc Reactor Pendant – Sterling Silver',
    description: 'Officially licensed arc reactor replica pendant in .925 sterling silver. Comes in gift box.',
    price: 3499,
    comparePrice: 4500,
    category: 'ornaments',
    franchise: 'Avengers',
    franchiseType: 'movie',
    tags: ['marvel', 'iron man', 'jewellery', 'pendant'],
    images: ['https://images.unsplash.com/photo-1617038260897-41a1f14a7f3c?q=80&w=800'],
    sku: 'IM-PNDNT-SS-001',
    stock: 40,
    sizes: [],
    colors: ['Silver'],
    rating: { average: 4.9, count: 212 },
  },
  // ─── Movie: Harry Potter ───────────────────────────────────────────────
  {
    name: 'Gryffindor House Robe',
    description: 'Screen-accurate Gryffindor robe in heavyweight poly-cotton. Includes embroidered crest.',
    price: 4299,
    comparePrice: 5500,
    category: 'clothing',
    franchise: 'Harry Potter',
    franchiseType: 'movie',
    tags: ['harry potter', 'gryffindor', 'robe', 'hogwarts'],
    images: ['https://images.unsplash.com/photo-1608889825271-9696280b2f6a?q=80&w=800'],
    sku: 'HP-ROBE-GRY-M',
    stock: 35,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Scarlet', 'Gold'],
    rating: { average: 4.8, count: 310 },
  },
  {
    name: 'Elder Wand Replica – Premium Edition',
    description: 'Detailed hand-painted elder wand replica. Collectible display packaging included.',
    price: 1899,
    category: 'accessories',
    franchise: 'Harry Potter',
    franchiseType: 'movie',
    tags: ['harry potter', 'wand', 'elder wand', 'collectible'],
    images: ['https://images.unsplash.com/photo-1621600411688-4be93b07b7d5?q=80&w=800'],
    sku: 'HP-WAND-ELDER-001',
    stock: 55,
    sizes: [],
    colors: ['Brown'],
    rating: { average: 4.7, count: 180 },
  },
  // ─── Show: Game of Thrones ─────────────────────────────────────────────
  {
    name: 'House Stark Direwolf Tee',
    description: 'Premium 180gsm cotton tee with House Stark sigil and "Winter is Coming" lettering.',
    price: 1199,
    category: 'clothing',
    franchise: 'Game of Thrones',
    franchiseType: 'show',
    tags: ['got', 'stark', 'house stark', 'tshirt'],
    images: ['https://images.unsplash.com/photo-1583744946564-b52ac1c389c8?q=80&w=800'],
    sku: 'GOT-TEE-STARK-M',
    stock: 100,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Dark Grey'],
    rating: { average: 4.7, count: 423 },
  },
  {
    name: 'Iron Throne Miniature Replica',
    description: 'Hand-crafted resin Iron Throne replica. Weighted base, 15 cm tall. Certificate of authenticity.',
    price: 2799,
    comparePrice: 3600,
    category: 'ornaments',
    franchise: 'Game of Thrones',
    franchiseType: 'show',
    tags: ['got', 'iron throne', 'collectible', 'decor'],
    images: ['https://images.unsplash.com/photo-1608889825313-0a8e8c0d4a9b?q=80&w=800'],
    sku: 'GOT-THRONE-MINI-001',
    stock: 25,
    sizes: [],
    colors: ['Steel Grey'],
    rating: { average: 4.9, count: 98 },
  },
  // ─── Show: Breaking Bad ────────────────────────────────────────────────
  {
    name: 'Heisenberg Silhouette Hoodie',
    description: 'Ultra-soft fleece hoodie with iconic Heisenberg hat silhouette print. "Say My Name" back-print.',
    price: 2599,
    category: 'clothing',
    franchise: 'Breaking Bad',
    franchiseType: 'show',
    tags: ['breaking bad', 'heisenberg', 'hoodie', 'walter white'],
    images: ['https://images.unsplash.com/photo-1520975922284-9e0ce827b2a1?q=80&w=800'],
    sku: 'BB-HOOD-HSNBG-L',
    stock: 70,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black'],
    rating: { average: 4.8, count: 265 },
  },
  {
    name: 'Los Pollos Hermanos Worker Cap',
    description: 'Embroidered cap in classic fast-food yellow. Adjustable snap-back. A must for the fans.',
    price: 699,
    category: 'accessories',
    franchise: 'Breaking Bad',
    franchiseType: 'show',
    tags: ['breaking bad', 'los pollos hermanos', 'cap', 'accessories'],
    images: ['https://images.unsplash.com/photo-1521369909029-2afed882baee?q=80&w=800'],
    sku: 'BB-CAP-LPH-001',
    stock: 180,
    sizes: ['One Size'],
    colors: ['Yellow'],
    rating: { average: 4.6, count: 189 },
  },
  // ─── Sports: FC Barcelona ──────────────────────────────────────────────
  {
    name: 'FC Barcelona Training Kit 2024',
    description: 'Official training top and shorts combo. Moisture-wicking, compression fit.',
    price: 3299,
    comparePrice: 4200,
    category: 'clothing',
    franchise: 'FC Barcelona',
    franchiseType: 'sports',
    tags: ['football', 'barcelona', 'training', 'la liga'],
    images: ['https://images.unsplash.com/photo-1522770179533-24471fcdba45?q=80&w=800'],
    sku: 'FCB-TRAIN-2024-L',
    stock: 45,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Blue', 'Red'],
    rating: { average: 4.5, count: 143 },
  },
  {
    name: 'FC Barcelona Leather Wallet',
    description: 'Genuine leather slim wallet with FC Barcelona crest emboss. 4 card slots, ID window.',
    price: 1299,
    category: 'accessories',
    franchise: 'FC Barcelona',
    franchiseType: 'sports',
    tags: ['football', 'barcelona', 'wallet', 'accessories'],
    images: ['https://images.unsplash.com/photo-1601597111158-2fceff292cdc?q=80&w=800'],
    sku: 'FCB-WALLET-LTH-001',
    stock: 90,
    sizes: [],
    colors: ['Black'],
    rating: { average: 4.4, count: 77 },
  },
];

exports.seedProducts = async () => {
  try {
    const Product = require('../models/Product');
    const count = await Product.countDocuments();
    if (count === 0) {
      await Product.insertMany(sampleProducts);
      console.log(`[product-service] Seeded ${sampleProducts.length} products`);
    } else {
      console.log(`[product-service] Database already has ${count} products – skipping seed`);
    }
  } catch (err) {
    console.error('[product-service] Seeding error:', err.message);
  }
};
